apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
        - name: http-echo
          image: mendhak/http-https-echo:38
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"